ERROR 2025-03-27 13:10:39,602 exception 36116 6200799232 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:10:55,966 exception 36116 6200799232 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:10:56,025 exception 36116 6217625600 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:10:56,601 exception 36116 6234451968 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:10:56,668 exception 36116 6251278336 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:08,373 exception 36153 6199209984 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:08,534 exception 36153 6216036352 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:25,570 exception 36153 6199209984 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:25,708 exception 36153 6216036352 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:26,301 exception 36153 6199209984 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:26,390 exception 36153 6232862720 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:27,251 exception 36153 6199209984 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:27,347 exception 36153 6216036352 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:41,911 exception 36153 6199209984 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:42,017 exception 36153 6232862720 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:42,551 exception 36153 6199209984 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:11:42,642 exception 36153 6216036352 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:12:19,962 exception 36153 6199209984 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-27 13:12:20,083 exception 36153 6232862720 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2025-03-28 07:28:26,068 log 25044 6130544640 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/petergangmei/Developer/Projects/django/quiz /app/views.py", line 15, in home
    return render(request, 'home.html', {'quizzes': quizzes})
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app' is not a registered namespace
ERROR 2025-03-28 07:28:26,071 log 25044 6147371008 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/petergangmei/Developer/Projects/django/quiz /app/views.py", line 15, in home
    return render(request, 'home.html', {'quizzes': quizzes})
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app' is not a registered namespace
ERROR 2025-03-28 07:28:26,079 basehttp 25044 6147371008 "GET / HTTP/1.1" 500 161454
ERROR 2025-03-28 07:29:01,163 log 27326 6200733696 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/petergangmei/Developer/Projects/django/quiz /app/views.py", line 15, in home
    return render(request, 'home.html', {'quizzes': quizzes})
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app' is not a registered namespace
ERROR 2025-03-28 07:29:01,168 basehttp 27326 6200733696 "GET / HTTP/1.1" 500 161454
ERROR 2025-03-28 07:29:05,827 log 27326 6200733696 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/petergangmei/Developer/Projects/django/quiz /app/views.py", line 15, in home
    return render(request, 'home.html', {'quizzes': quizzes})
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app' is not a registered namespace
ERROR 2025-03-28 07:29:05,830 basehttp 27326 6200733696 "GET / HTTP/1.1" 500 161454
ERROR 2025-03-28 07:29:52,941 log 27404 6199980032 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/petergangmei/Developer/Projects/django/quiz /app/views.py", line 15, in home
    return render(request, 'home.html', {'quizzes': quizzes})
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app' is not a registered namespace
ERROR 2025-03-28 07:29:52,946 basehttp 27404 6199980032 "GET / HTTP/1.1" 500 161454
ERROR 2025-03-28 07:29:54,473 log 27404 6216806400 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/petergangmei/Developer/Projects/django/quiz /app/views.py", line 15, in home
    return render(request, 'home.html', {'quizzes': quizzes})
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app' is not a registered namespace
ERROR 2025-03-28 07:29:54,477 basehttp 27404 6216806400 "GET / HTTP/1.1" 500 161454
ERROR 2025-03-28 07:37:48,361 log 27421 6146781184 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/petergangmei/Developer/Projects/django/quiz /app/views.py", line 15, in home
    return render(request, 'home.html', {'quizzes': quizzes})
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app' is not a registered namespace
ERROR 2025-03-28 07:37:48,370 basehttp 27421 6146781184 "GET / HTTP/1.1" 500 162187
ERROR 2025-03-28 07:37:53,621 log 27421 6129954816 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/petergangmei/Developer/Projects/django/quiz /app/views.py", line 15, in home
    return render(request, 'home.html', {'quizzes': quizzes})
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app' is not a registered namespace
ERROR 2025-03-28 07:37:53,625 basehttp 27421 6129954816 "GET / HTTP/1.1" 500 161454
ERROR 2025-03-28 07:38:02,070 log 27421 6146781184 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/petergangmei/Developer/Projects/django/quiz /app/views.py", line 15, in home
    return render(request, 'home.html', {'quizzes': quizzes})
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/petergangmei/Developer/Projects/django/quiz /venv/lib/python3.13/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app' is not a registered namespace
ERROR 2025-03-28 07:38:02,073 basehttp 27421 6146781184 "GET / HTTP/1.1" 500 162452
